version: '3.8'

networks:
  default:
    external:
      name: apps

services:
  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - '8282:80'
    command: nginx -g 'daemon off;'
    volumes:
      - ./nginx/default/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/default/php.conf:/etc/nginx/php.conf
      - /path/to/your/projects/directory/myproject-php-8:/home/dev/apps/myproject-php-8
      - /path/to/your/projects/directory/myproject-php-74:/home/dev/apps/myproject-php-74
      - /path/to/your/projects/directory/myproject-php-73:/home/dev/apps/myproject-php-73
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - php_8
      - php_7_4
      - php_7_3

  mysql_8:
    image: mysql:8.0.28
    restart: unless-stopped
    tty: true
    ports:
      - '33080:3306'
    volumes:
      - ./mysql-8-data:/var/lib/mysql
    environment:
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_8

  mysql_5:
    image: mysql:5.7.37
    restart: unless-stopped
    tty: true
    ports:
      - '33057:3306'
    volumes:
      - ./mysql-5-data:/var/lib/mysql
    environment:
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_5

  php_8:
    build:
      context: .
      dockerfile: php_8.Dockerfile
    restart: unless-stopped
    volumes:
      - /path/to/your/projects/directory/myproject-php-8:/home/dev/apps/myproject-php-8
      - /etc/localtime:/etc/localtime:ro

  php_7_4:
    build:
      context: .
      dockerfile: php_7_4.Dockerfile
    restart: unless-stopped
    volumes:
      - /path/to/your/projects/directory/myproject-php-74:/home/dev/apps/myproject-php-74
      - /etc/localtime:/etc/localtime:ro

  php_7_3:
    build:
      context: .
      dockerfile: php_7_3.Dockerfile
    restart: unless-stopped
    volumes:
      - /path/to/your/projects/directory/myproject-php-73:/home/dev/apps/myproject-php-73
      - /etc/localtime:/etc/localtime:ro
