version: '3.8'

networks:
  default:
    name: apps

services:
  nginx:
    image: nginx:1.23.0-alpine
    ports:
      - '8282:80'
    command: nginx -g 'daemon off;'
    volumes:
      # load nginx config
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/config/php.conf:/etc/nginx/php.conf
      # mount your nginx project virtual hosts
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      # mount your project directories to connect them with nginx
      - ../projects/:/home/dev/apps/
      # mount your system's local timezone settings (for WSL2, Linux distros)
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - php_8_1
      - php_8
      - php_7_4
      - php_7_3

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    logging:
      driver: 'none'
    ports:
      - '1025:1025'
      - '8025:8025'

  mysql_8:
    image: mysql:8.0.28
    restart: unless-stopped
    tty: true
    container_name: mysql8
    ports:
      - '33080:3306'
    volumes:
      # mount your MySQL 8 data directory
      - ./volumes/mysql-8-data:/var/lib/mysql
    environment:
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_8

  mysql_5:
    image: mysql:5.7.37
    restart: unless-stopped
    tty: true
    container_name: mysql5
    ports:
      - '33057:3306'
    volumes:
      # mount your MySQL 5.7 data directory
      - ./volumes/mysql-5-data:/var/lib/mysql
    environment:
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_5

  php_8_1:
    build:
      context: .
      dockerfile: php_8_1.Dockerfile
    restart: unless-stopped
    container_name: php81
    volumes:
      # mount your PHP 8.1 projects
      - ../projects/first-php-81-app:/home/dev/apps/first-php-81-app
      - ../projects/second-php-81-app:/home/dev/apps/second-php-81-app
      # - ../projects/third-php-81-app:/home/dev/apps/third-php-81-app
      # - ../projects/fourth-php-81-app:/home/dev/apps/fourth-php-81-app
      - /etc/localtime:/etc/localtime:ro

  php_8:
    build:
      context: .
      dockerfile: php_8.Dockerfile
    container_name: php8
    restart: unless-stopped
    volumes:
      # mount your PHP 8.0 projects
      - ../projects/first-php-8-app:/home/dev/apps/first-php-8-app
      - ../projects/second-php-8-app:/home/dev/apps/second-php-8-app
      # - ../projects/third-php-8-app:/home/dev/apps/third-php-8-app
      # - ../projects/fourth-php-8-app:/home/dev/apps/fourth-php-8-app
      - /etc/localtime:/etc/localtime:ro

  php_7_4:
    build:
      context: .
      dockerfile: php_7_4.Dockerfile
    container_name: php74
    restart: unless-stopped
    volumes:
      # mount your PHP 7.4 projects
      - ../projects/first-php-74-app:/home/dev/apps/first-php-74-app
      - ../projects/second-php-74-app:/home/dev/apps/second-php-74-app
      # - ../projects/third-php-74-app:/home/dev/apps/third-php-74-app
      # - ../projects/fourth-php-74-app:/home/dev/apps/fourth-php-74-app
      - /etc/localtime:/etc/localtime:ro

  php_7_3:
    build:
      context: .
      dockerfile: php_7_3.Dockerfile
    container_name: php73
    restart: unless-stopped
    volumes:
      # mount your PHP 7.3 projects
      - ../projects/first-php-73-app:/home/dev/apps/first-php-73-app
      - ../projects/second-php-73-app:/home/dev/apps/second-php-73-app
      # - ../projects/third-php-73-app:/home/dev/apps/third-php-73-app
      # - ../projects/fourth-php-73-app:/home/dev/apps/fourth-php-73-app
      - /etc/localtime:/etc/localtime:ro
